// <auto-generated />
using System;
using FirmaElectronica.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirmaElectronica.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FirmaElectronicaDbContext))]
    partial class FirmaElectronicaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashFirmado")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HashOriginal")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdComprobanteOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdSistemaOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreArchivoOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("RutaConstancia")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RutaPdfFirmado")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RutaPdfOriginal")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdEmpresa", "IdSistemaOrigen", "IdComprobanteOrigen");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ColorPrincipal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Dominio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("CUIT")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.EventoAuditoria", b =>
                {
                    b.Property<Guid>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DatosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaHoraUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashDocumentoEnEvento")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IP")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("IdDocumento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdFirmante")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdEvento");

                    b.HasIndex("IdFirmante");

                    b.HasIndex("IdDocumento", "FechaHoraUTC");

                    b.ToTable("EventosAuditoria");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.Firmante", b =>
                {
                    b.Property<Guid>("IdFirmante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CUIT_DNI")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Celular")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EstadoFirma")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVista")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdDocumento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrdenFirma")
                        .HasColumnType("int");

                    b.Property<string>("RutaFirmaImagen")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdFirmante");

                    b.HasIndex("IdDocumento");

                    b.ToTable("Firmantes");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.SolicitudFirma", b =>
                {
                    b.Property<Guid>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdDocumento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFirmante")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdFirmante");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("SolicitudesFirma");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.UsuarioApi", b =>
                {
                    b.Property<Guid>("IdUsuarioApi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UltimoUso")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuarioApi");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.HasIndex("IdEmpresa");

                    b.ToTable("UsuariosApi");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.Documento", b =>
                {
                    b.HasOne("FirmaElectronica.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Documentos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.EventoAuditoria", b =>
                {
                    b.HasOne("FirmaElectronica.Domain.Entities.Documento", "Documento")
                        .WithMany("EventosAuditoria")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmaElectronica.Domain.Entities.Firmante", "Firmante")
                        .WithMany()
                        .HasForeignKey("IdFirmante")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Documento");

                    b.Navigation("Firmante");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.Firmante", b =>
                {
                    b.HasOne("FirmaElectronica.Domain.Entities.Documento", "Documento")
                        .WithMany("Firmantes")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.SolicitudFirma", b =>
                {
                    b.HasOne("FirmaElectronica.Domain.Entities.Documento", "Documento")
                        .WithMany("SolicitudesFirma")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmaElectronica.Domain.Entities.Firmante", "Firmante")
                        .WithMany("SolicitudesFirma")
                        .HasForeignKey("IdFirmante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Firmante");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.UsuarioApi", b =>
                {
                    b.HasOne("FirmaElectronica.Domain.Entities.Empresa", "Empresa")
                        .WithMany("UsuariosApi")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.Documento", b =>
                {
                    b.Navigation("EventosAuditoria");

                    b.Navigation("Firmantes");

                    b.Navigation("SolicitudesFirma");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("UsuariosApi");
                });

            modelBuilder.Entity("FirmaElectronica.Domain.Entities.Firmante", b =>
                {
                    b.Navigation("SolicitudesFirma");
                });
#pragma warning restore 612, 618
        }
    }
}
